const brandLogoSlugs: Record<string, string> = {
  "airbnb": "airbnb",
  "amazon": "amazon",
  "amazon prime": "amazonprime",
  "apple": "apple",
  "apple tv+": "appletv",
  "best buy": "bestbuy",
  "burger king": "burgerking",
  "bath & body works": "bathandbodyworks",
  "chick-fil-a": "chickfila",
  "chipotle": "chipotle",
  "costco": "costco",
  "cvs pharmacy": "cvshealth",
  "delta air lines": "delta",
  "discord nitro": "discord",
  "disney+": "disneyplus",
  "domino's": "dominos",
  "doordash": "doordash",
  "dunkin'": "dunkin",
  "ea play": "ea",
  "ebay": "ebay",
  "epic games": "epicgames",
  "etsy": "etsy",
  "expedia": "expedia",
  "fandango": "fandango",
  "fortnite": "fortnite",
  "gamestop": "gamestop",
  "glossier": "glossier",
  "grubhub": "grubhub",
  "hbo max": "max",
  "home depot": "homedepot",
  "hotels.com": "hotelsdotcom",
  "hulu": "hulu",
  "ikea": "ikea",
  "instacart": "instacart",
  "krispy kreme": "krispykreme",
  "league of legends": "leagueoflegends",
  "lowe's": "lowes",
  "lyft": "lyft",
  "mcdonald's": "mcdonalds",
  "minecraft": "minecraft",
  "netflix": "netflix",
  "nike": "nike",
  "nintendo": "nintendo",
  "nordstrom": "nordstrom",
  "paramount+": "paramountplus",
  "playstation": "playstation",
  "razer": "razer",
  "razer gold": "razer",
  "roblox": "roblox",
  "sephora": "sephora",
  "sling tv": "sling",
  "spotify": "spotify",
  "starbucks": "starbucks",
  "steam": "steam",
  "subway": "subway",
  "taco bell": "tacobell",
  "target": "target",
  "the coffee bean & tea leaf": "thecoffeebeanandtealeaf",
  "tim hortons": "timhortons",
  "twitch": "twitch",
  "uber": "uber",
  "uber eats": "ubereats",
  "united airlines": "unitedairlines",
  "ulta beauty": "ulta",
  "visa": "visa",
  "walgreens": "walgreens",
  "walmart": "walmart",
  "xbox": "xbox",
  "xbox game pass": "xbox",
  "youtube": "youtube"
};

const brandLogoDomains: Record<string, string> = {
  "airbnb": "airbnb.com",
  "amazon": "amazon.com",
  "amazon prime": "amazon.com",
  "apple": "apple.com",
  "apple tv+": "apple.com",
  "best buy": "bestbuy.com",
  "bath & body works": "bathandbodyworks.com",
  "burger king": "bk.com",
  "chick-fil-a": "chick-fil-a.com",
  "chipotle": "chipotle.com",
  "costco": "costco.com",
  "cvs pharmacy": "cvs.com",
  "delta air lines": "delta.com",
  "discord nitro": "discord.com",
  "disney+": "disneyplus.com",
  "domino's": "dominos.com",
  "doordash": "doordash.com",
  "dutch bros": "dutchbros.com",
  "dunkin'": "dunkindonuts.com",
  "ea play": "ea.com",
  "ebay": "ebay.com",
  "epic games": "epicgames.com",
  "etsy": "etsy.com",
  "expedia": "expedia.com",
  "fandango": "fandango.com",
  "fenty beauty": "fentybeauty.com",
  "gamestop": "gamestop.com",
  "glossier": "glossier.com",
  "grubhub": "grubhub.com",
  "hbo max": "max.com",
  "home depot": "homedepot.com",
  "hotels.com": "hotels.com",
  "hulu": "hulu.com",
  "ikea": "ikea.com",
  "instacart": "instacart.com",
  "krispy kreme": "krispykreme.com",
  "league of legends": "leagueoflegends.com",
  "lowe's": "lowes.com",
  "lyft": "lyft.com",
  "mac cosmetics": "maccosmetics.com",
  "marriott": "marriott.com",
  "mcdonald's": "mcdonalds.com",
  "netflix": "netflix.com",
  "nike": "nike.com",
  "nintendo": "nintendo.com",
  "nordstrom": "nordstrom.com",
  "paramount+": "paramountplus.com",
  "playstation": "playstation.com",
  "razer": "razer.com",
  "razer gold": "razer.com",
  "roblox": "roblox.com",
  "sephora": "sephora.com",
  "sling tv": "sling.com",
  "spotify": "spotify.com",
  "starbucks": "starbucks.com",
  "steam": "steampowered.com",
  "subway": "subway.com",
  "taco bell": "tacobell.com",
  "target": "target.com",
  "the coffee bean & tea leaf": "coffeebean.com",
  "tim hortons": "timhortons.com",
  "twitch": "twitch.tv",
  "uber": "uber.com",
  "uber eats": "ubereats.com",
  "united airlines": "united.com",
  "ulta beauty": "ulta.com",
  "valorant": "playvalorant.com",
  "visa": "visa.com",
  "walgreens": "walgreens.com",
  "walmart": "walmart.com",
  "wayfair": "wayfair.com",
  "xbox": "xbox.com",
  "xbox game pass": "xbox.com",
  "youtube": "youtube.com"
};

const brandLogoColors: Record<string, string> = {
  "amazon": "ffffff",
  "amazon prime": "ffffff",
  "apple": "111827",
  "apple tv+": "ffffff",
  "best buy": "0046be",
  "doordash": "ffffff",
  "ebay": "ffffff",
  "hulu": "111111",
  "mastercard": "ffffff",
  "netflix": "e50914",
  "playstation": "ffffff",
  "razer": "44d62c",
  "razer gold": "44d62c",
  "starbucks": "ffffff",
  "steam": "ffffff",
  "target": "ffffff",
  "visa": "ffffff",
  "walmart": "ffc220",
  "xbox": "ffffff"
};

const brandLocalLogoFiles: Record<string, string> = {
  "amazon prime": "amazon-prime",
  "apple tv+": "apple-tv",
  "bath & body works": "bath-body-works",
  "best buy": "best-buy",
  "burger king": "burger-king",
  "chick-fil-a": "chick-fil-a",
  "cvs pharmacy": "cvs-pharmacy",
  "delta air lines": "delta-air-lines",
  "discord nitro": "discord-nitro",
  "disney+": "disney-plus",
  "domino's": "dominos",
  "dunkin'": "dunkin",
  "ea play": "ea-play",
  "epic games": "epic-games",
  "hbo max": "hbo-max",
  "home depot": "home-depot",
  "hotels.com": "hotels-com",
  "krispy kreme": "krispy-kreme",
  "league of legends": "league-of-legends",
  "lowe's": "lowes",
  "mcdonald's": "mcdonalds",
  "paramount+": "paramount-plus",
  "razer gold": "razer-gold",
  "sling tv": "sling-tv",
  "taco bell": "taco-bell",
  "the coffee bean & tea leaf": "the-coffee-bean-tea-leaf",
  "tim hortons": "tim-hortons",
  "uber eats": "uber-eats",
  "ulta beauty": "ulta-beauty",
  "xbox game pass": "xbox"
};

export function getBrandLogoSlug(brand: string) {
  return brandLogoSlugs[brand.toLowerCase()];
}

export function getBrandLogoSources(brand: string, color?: string) {
  const key = brand.toLowerCase();
  const slug = getBrandLogoSlug(brand);
  const domain = brandLogoDomains[key];
  const logoColor = color || brandLogoColors[key] || "ffffff";
  const localLogoFile =
    brandLocalLogoFiles[key] ||
    key.replaceAll("&", "and").replaceAll("+", "plus").replaceAll("'", "").replaceAll(".", "-").replaceAll(" ", "-");
  const sources: string[] = [];

  sources.push(`/brand-logos/${localLogoFile}.svg`);
  if (slug) sources.push(`https://cdn.simpleicons.org/${slug}/${logoColor.replace("#", "")}`);
  if (domain) {
    sources.push(`https://logo.clearbit.com/${domain}`);
    sources.push(`https://www.google.com/s2/favicons?domain=${domain}&sz=128`);
  }

  return [...new Set(sources)];
}

export function getBrandLogoUrl(brand: string, color?: string) {
  return getBrandLogoSources(brand, color)[0] || "";
}
